### ISSUE TITLE
Drone Explosion Sound Possibly too Loud

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#163]
"Bamboofats: Since the original game, The Kushan drone frigate drones explode and replenish themselves. But the sound of the explosion is really loud for such small items. Is this something that the patch can modify?"
See "privatechatmessagereceived.lua" for how to adjust the volume of a sound.

**Comment by Gunnerth** [comment]
The loudness of the explosion is due to playing the medium explosion sound, which is intended for corvettes, and it plays 8 explosions simultaneously, which makes it sound louder. 

Changed the kus_drone0.event from
{ "sound", "EXPLOSION/MEDIUM/ETG_EXPLODE_MEDIUM_FIREY" },
to
{ "sound", "EXPLOSION/SMALL/ETG_EXPLODE_SMALL_PLASMA" },

Also adding an event file to every other drone and removing the sound/explosion section will help reduce the issue.

**Comment by FearStream** [comment]
https://github.com/HW-PlayersPatch/Development/pulls

**Comment by Novaras** [comment]
https://github.com/HW-PlayersPatch/Development/pulls
