### ISSUE TITLE
Early Game HW2 vs HW1

### ISSUE THREAD

**Issue by cloaked2222** [HW-PlayersPatch/Development#267]
Fear: "hw1 early is obnoxious"

Potential hw1 early nerfs:
A) Adding bomber tech back in at 400ru/40sec.
B) The following three 100ru changes would be to correct my rushed research costs for b11: Add 100ru to kus_corvettechassis, add 100 ru to kus_capitalshipdrive, add 100ru to kus_capitalshipchassis. 
C) Could make most all hw1 corvs build 1 second slower (revert a 2.4 buff).
etc.

**Comment by Novaras** [comment]
A) is a good idea overall, I have no issues with this whatsoever
B) is inferior to A and I generally think hw1 tech is overpriced outside the fighters
C) this has too much impact throughout the whole span of the game, we're already in the mind that HW1 swarm remaxing is borderline unfair in comparison to HW2s free redocks with no concession coming from capitals due to their astronomical price right now

**Comment by SirBattlestar** [comment]
Becouse we cant controll map pool, we lack an important aspect of balancing. Most players are ok with hw1 being unbalanced against hw2 on small map as long as it is known an regarded as a unfair machup.(on the smallest maps) as it stands today alot of people are not aware, and defend their wins on shield ect, as fair and balanced. becouse we can not change the map pool, a statement on pool balancing issues on the forums would atleast help to avoid alot of salty arguments regarding hw1 vs hw2.

**Comment by Novaras** [comment]
https://github.com/HW-PlayersPatch/Development/pull/272
